package net.fantesy84.sys.customer.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.fantesy84.sys.user.domain.EpSysUser;

/**
 * EpSysCust generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_CUST", catalog = "EASY_PAY")
public class EpSysCust implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7661284252462527858L;
	private Integer autoId;
	private String custName;
	private String custType;
	private Date createTime;
	private Date updateTime;
	private Boolean deleteFlag;
	private Set<EpSysUser> epSysUsers = new HashSet<EpSysUser>(0);

	public EpSysCust() {
	}

	public EpSysCust(String custName, String custType, Date createTime) {
		this.custName = custName;
		this.custType = custType;
		this.createTime = createTime;
	}

	public EpSysCust(String custName, String custType, Date createTime, Date updateTime, Boolean deleteFlag,
			Set<EpSysUser> epSysUsers) {
		this.custName = custName;
		this.custType = custType;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
		this.epSysUsers = epSysUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@Column(name = "CUST_NAME", nullable = false, length = 40)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "CUST_TYPE", nullable = false, length = 12)
	public String getCustType() {
		return this.custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epSysCust")
	public Set<EpSysUser> getEpSysUsers() {
		return this.epSysUsers;
	}

	public void setEpSysUsers(Set<EpSysUser> epSysUsers) {
		this.epSysUsers = epSysUsers;
	}

}
