package net.fantesy84.sys.customer.domain;
// Generated 2016-4-13 22:00:27 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpSysUser generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_USER", catalog = "EASY_PAY")
public class EpSysUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8939578133268588915L;
	private Integer autoId;
	private EpSysCust epSysCust;
	private String username;
	private String passwd;
	private String realName;
	private boolean deleteFlag;
	private Set<EpSysAccount> epSysAccounts = new HashSet<EpSysAccount>(0);

	public EpSysUser() {
	}

	public EpSysUser(EpSysCust epSysCust, String username, String passwd, String realName, boolean deleteFlag) {
		this.epSysCust = epSysCust;
		this.username = username;
		this.passwd = passwd;
		this.realName = realName;
		this.deleteFlag = deleteFlag;
	}

	public EpSysUser(EpSysCust epSysCust, String username, String passwd, String realName, boolean deleteFlag,
			Set<EpSysAccount> epSysAccounts) {
		this.epSysCust = epSysCust;
		this.username = username;
		this.passwd = passwd;
		this.realName = realName;
		this.deleteFlag = deleteFlag;
		this.epSysAccounts = epSysAccounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUST_ID", nullable = false)
	public EpSysCust getEpSysCust() {
		return this.epSysCust;
	}

	public void setEpSysCust(EpSysCust epSysCust) {
		this.epSysCust = epSysCust;
	}

	@Column(name = "USERNAME", nullable = false, length = 40)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWD", nullable = false, length = 160)
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "REAL_NAME", nullable = false, length = 60)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "DELETE_FLAG", nullable = false)
	public boolean isDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epSysUser")
	public Set<EpSysAccount> getEpSysAccounts() {
		return this.epSysAccounts;
	}

	public void setEpSysAccounts(Set<EpSysAccount> epSysAccounts) {
		this.epSysAccounts = epSysAccounts;
	}

}
