package net.fantesy84.sys.solution.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpSysSolutionBaseFee generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_SOLUTION_BASE_FEE", catalog = "EASY_PAY")
public class EpSysSolutionBaseFee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2297720327813489700L;
	private Integer autoId;
	private EpSysSolution epSysSolution;
	private String paymentWay;
	private String paymentMethod;
	private BigDecimal staticFee;
	private Double staticScale;
	private BigDecimal maxTrans;
	private BigDecimal minTrans;
	private BigDecimal maxCharge;
	private BigDecimal minCharge;
	private Double feeScale;
	private Date createTime;
	private Date updateTime;
	private Boolean deleteFlag;

	public EpSysSolutionBaseFee() {
	}

	public EpSysSolutionBaseFee(EpSysSolution epSysSolution, String paymentWay, String paymentMethod, Date createTime) {
		this.epSysSolution = epSysSolution;
		this.paymentWay = paymentWay;
		this.paymentMethod = paymentMethod;
		this.createTime = createTime;
	}

	public EpSysSolutionBaseFee(EpSysSolution epSysSolution, String paymentWay, String paymentMethod,
			BigDecimal staticFee, Double staticScale, BigDecimal maxTrans, BigDecimal minTrans, BigDecimal maxCharge,
			BigDecimal minCharge, Double feeScale, Date createTime, Date updateTime, Boolean deleteFlag) {
		this.epSysSolution = epSysSolution;
		this.paymentWay = paymentWay;
		this.paymentMethod = paymentMethod;
		this.staticFee = staticFee;
		this.staticScale = staticScale;
		this.maxTrans = maxTrans;
		this.minTrans = minTrans;
		this.maxCharge = maxCharge;
		this.minCharge = minCharge;
		this.feeScale = feeScale;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SLT_ID", nullable = false)
	public EpSysSolution getEpSysSolution() {
		return this.epSysSolution;
	}

	public void setEpSysSolution(EpSysSolution epSysSolution) {
		this.epSysSolution = epSysSolution;
	}

	@Column(name = "PAYMENT_WAY", nullable = false, length = 7)
	public String getPaymentWay() {
		return this.paymentWay;
	}

	public void setPaymentWay(String paymentWay) {
		this.paymentWay = paymentWay;
	}

	@Column(name = "PAYMENT_METHOD", nullable = false, length = 7)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "STATIC_FEE", precision = 20)
	public BigDecimal getStaticFee() {
		return this.staticFee;
	}

	public void setStaticFee(BigDecimal staticFee) {
		this.staticFee = staticFee;
	}

	@Column(name = "STATIC_SCALE", precision = 22, scale = 0)
	public Double getStaticScale() {
		return this.staticScale;
	}

	public void setStaticScale(Double staticScale) {
		this.staticScale = staticScale;
	}

	@Column(name = "MAX_TRANS", precision = 20)
	public BigDecimal getMaxTrans() {
		return this.maxTrans;
	}

	public void setMaxTrans(BigDecimal maxTrans) {
		this.maxTrans = maxTrans;
	}

	@Column(name = "MIN_TRANS", precision = 20)
	public BigDecimal getMinTrans() {
		return this.minTrans;
	}

	public void setMinTrans(BigDecimal minTrans) {
		this.minTrans = minTrans;
	}

	@Column(name = "MAX_CHARGE", precision = 20)
	public BigDecimal getMaxCharge() {
		return this.maxCharge;
	}

	public void setMaxCharge(BigDecimal maxCharge) {
		this.maxCharge = maxCharge;
	}

	@Column(name = "MIN_CHARGE", precision = 20)
	public BigDecimal getMinCharge() {
		return this.minCharge;
	}

	public void setMinCharge(BigDecimal minCharge) {
		this.minCharge = minCharge;
	}

	@Column(name = "FEE_SCALE", precision = 22, scale = 0)
	public Double getFeeScale() {
		return this.feeScale;
	}

	public void setFeeScale(Double feeScale) {
		this.feeScale = feeScale;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
