package net.fantesy84.sys.solution.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpSysSolutionBaseCashier generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_SOLUTION_BASE_CASHIER", catalog = "EASY_PAY")
public class EpSysSolutionBaseCashier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5673246710041502336L;
	private Integer autoId;
	private EpSysSolution epSysSolution;
	private String patmentCustType;
	private String paymentType;
	private int sort;
	private Date createTime;
	private Date updateTime;
	private Boolean deleteFlag;

	public EpSysSolutionBaseCashier() {
	}

	public EpSysSolutionBaseCashier(EpSysSolution epSysSolution, String patmentCustType, String paymentType, int sort,
			Date createTime, Date updateTime) {
		this.epSysSolution = epSysSolution;
		this.patmentCustType = patmentCustType;
		this.paymentType = paymentType;
		this.sort = sort;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public EpSysSolutionBaseCashier(EpSysSolution epSysSolution, String patmentCustType, String paymentType, int sort,
			Date createTime, Date updateTime, Boolean deleteFlag) {
		this.epSysSolution = epSysSolution;
		this.patmentCustType = patmentCustType;
		this.paymentType = paymentType;
		this.sort = sort;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SLT_ID", nullable = false)
	public EpSysSolution getEpSysSolution() {
		return this.epSysSolution;
	}

	public void setEpSysSolution(EpSysSolution epSysSolution) {
		this.epSysSolution = epSysSolution;
	}

	@Column(name = "PATMENT_CUST_TYPE", nullable = false, length = 12)
	public String getPatmentCustType() {
		return this.patmentCustType;
	}

	public void setPatmentCustType(String patmentCustType) {
		this.patmentCustType = patmentCustType;
	}

	@Column(name = "PAYMENT_TYPE", nullable = false, length = 12)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "SORT", nullable = false)
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
