package net.fantesy84.sys.solution.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * EpSysSolution generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_SOLUTION", catalog = "EASY_PAY")
public class EpSysSolution implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5316173188700304193L;
	private Integer autoId;
	private int version;
	private String sltName;
	private String sltCode;
	private String sltType;
	private Boolean transPermissions;
	private String feeTaker;
	private Integer settlementCycle;
	private BigDecimal minimumSettlement;
	private String currencyType;
	private Date createTime;
	private Date updateTime;
	private boolean deleteFlag;
	private Set<EpSysSolutionBaseFee> epSysSolutionBaseFees = new HashSet<EpSysSolutionBaseFee>(0);
	private Set<EpSysAcctSltRels> epSysAcctSltRelses = new HashSet<EpSysAcctSltRels>(0);
	private Set<EpSysSolutionBaseCashier> epSysSolutionBaseCashiers = new HashSet<EpSysSolutionBaseCashier>(0);
	private Set<EpSysSolutionSettlementChanel> epSysSolutionSettlementChanels = new HashSet<EpSysSolutionSettlementChanel>(
			0);

	public EpSysSolution() {
	}

	public EpSysSolution(String sltName, String sltCode, String sltType, Date createTime, boolean deleteFlag) {
		this.sltName = sltName;
		this.sltCode = sltCode;
		this.sltType = sltType;
		this.createTime = createTime;
		this.deleteFlag = deleteFlag;
	}

	public EpSysSolution(String sltName, String sltCode, String sltType, Boolean transPermissions, String feeTaker,
			Integer settlementCycle, BigDecimal minimumSettlement, String currencyType, Date createTime,
			Date updateTime, boolean deleteFlag, Set<EpSysSolutionBaseFee> epSysSolutionBaseFees,
			Set<EpSysAcctSltRels> epSysAcctSltRelses, Set<EpSysSolutionBaseCashier> epSysSolutionBaseCashiers,
			Set<EpSysSolutionSettlementChanel> epSysSolutionSettlementChanels) {
		this.sltName = sltName;
		this.sltCode = sltCode;
		this.sltType = sltType;
		this.transPermissions = transPermissions;
		this.feeTaker = feeTaker;
		this.settlementCycle = settlementCycle;
		this.minimumSettlement = minimumSettlement;
		this.currencyType = currencyType;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
		this.epSysSolutionBaseFees = epSysSolutionBaseFees;
		this.epSysAcctSltRelses = epSysAcctSltRelses;
		this.epSysSolutionBaseCashiers = epSysSolutionBaseCashiers;
		this.epSysSolutionSettlementChanels = epSysSolutionSettlementChanels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "SLT_NAME", nullable = false, length = 20)
	public String getSltName() {
		return this.sltName;
	}

	public void setSltName(String sltName) {
		this.sltName = sltName;
	}

	@Column(name = "SLT_CODE", nullable = false, length = 32)
	public String getSltCode() {
		return this.sltCode;
	}

	public void setSltCode(String sltCode) {
		this.sltCode = sltCode;
	}

	@Column(name = "SLT_TYPE", nullable = false, length = 7)
	public String getSltType() {
		return this.sltType;
	}

	public void setSltType(String sltType) {
		this.sltType = sltType;
	}

	@Column(name = "TRANS_PERMISSIONS")
	public Boolean getTransPermissions() {
		return this.transPermissions;
	}

	public void setTransPermissions(Boolean transPermissions) {
		this.transPermissions = transPermissions;
	}

	@Column(name = "FEE_TAKER", length = 8)
	public String getFeeTaker() {
		return this.feeTaker;
	}

	public void setFeeTaker(String feeTaker) {
		this.feeTaker = feeTaker;
	}

	@Column(name = "SETTLEMENT_CYCLE")
	public Integer getSettlementCycle() {
		return this.settlementCycle;
	}

	public void setSettlementCycle(Integer settlementCycle) {
		this.settlementCycle = settlementCycle;
	}

	@Column(name = "MINIMUM_SETTLEMENT", precision = 20)
	public BigDecimal getMinimumSettlement() {
		return this.minimumSettlement;
	}

	public void setMinimumSettlement(BigDecimal minimumSettlement) {
		this.minimumSettlement = minimumSettlement;
	}

	@Column(name = "CURRENCY_TYPE", length = 7)
	public String getCurrencyType() {
		return this.currencyType;
	}

	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "DELETE_FLAG", nullable = false)
	public boolean isDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epSysSolution")
	public Set<EpSysSolutionBaseFee> getEpSysSolutionBaseFees() {
		return this.epSysSolutionBaseFees;
	}

	public void setEpSysSolutionBaseFees(Set<EpSysSolutionBaseFee> epSysSolutionBaseFees) {
		this.epSysSolutionBaseFees = epSysSolutionBaseFees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epSysSolution")
	public Set<EpSysAcctSltRels> getEpSysAcctSltRelses() {
		return this.epSysAcctSltRelses;
	}

	public void setEpSysAcctSltRelses(Set<EpSysAcctSltRels> epSysAcctSltRelses) {
		this.epSysAcctSltRelses = epSysAcctSltRelses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epSysSolution")
	public Set<EpSysSolutionBaseCashier> getEpSysSolutionBaseCashiers() {
		return this.epSysSolutionBaseCashiers;
	}

	public void setEpSysSolutionBaseCashiers(Set<EpSysSolutionBaseCashier> epSysSolutionBaseCashiers) {
		this.epSysSolutionBaseCashiers = epSysSolutionBaseCashiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epSysSolution")
	public Set<EpSysSolutionSettlementChanel> getEpSysSolutionSettlementChanels() {
		return this.epSysSolutionSettlementChanels;
	}

	public void setEpSysSolutionSettlementChanels(Set<EpSysSolutionSettlementChanel> epSysSolutionSettlementChanels) {
		this.epSysSolutionSettlementChanels = epSysSolutionSettlementChanels;
	}

}
