package net.fantesy84.sys.solution.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpSysSolutionSettlementChanel generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_SOLUTION_SETTLEMENT_CHANEL", catalog = "EASY_PAY")
public class EpSysSolutionSettlementChanel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7784789388121015008L;
	private Integer autoId;
	private EpSysSolution epSysSolution;
	private Boolean isActive;
	private int acctId;
	private int settlementBackId;
	private Date createTime;
	private Date upadteTime;
	private Boolean deleteFlag;

	public EpSysSolutionSettlementChanel() {
	}

	public EpSysSolutionSettlementChanel(EpSysSolution epSysSolution, int acctId, int settlementBackId, Date createTime,
			Date upadteTime) {
		this.epSysSolution = epSysSolution;
		this.acctId = acctId;
		this.settlementBackId = settlementBackId;
		this.createTime = createTime;
		this.upadteTime = upadteTime;
	}

	public EpSysSolutionSettlementChanel(EpSysSolution epSysSolution, Boolean isActive, int acctId,
			int settlementBackId, Date createTime, Date upadteTime, Boolean deleteFlag) {
		this.epSysSolution = epSysSolution;
		this.isActive = isActive;
		this.acctId = acctId;
		this.settlementBackId = settlementBackId;
		this.createTime = createTime;
		this.upadteTime = upadteTime;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SLT_ID", nullable = false)
	public EpSysSolution getEpSysSolution() {
		return this.epSysSolution;
	}

	public void setEpSysSolution(EpSysSolution epSysSolution) {
		this.epSysSolution = epSysSolution;
	}

	@Column(name = "IS_ACTIVE")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "ACCT_ID", nullable = false)
	public int getAcctId() {
		return this.acctId;
	}

	public void setAcctId(int acctId) {
		this.acctId = acctId;
	}

	@Column(name = "SETTLEMENT_BACK_ID", nullable = false)
	public int getSettlementBackId() {
		return this.settlementBackId;
	}

	public void setSettlementBackId(int settlementBackId) {
		this.settlementBackId = settlementBackId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPADTE_TIME", nullable = false, length = 19)
	public Date getUpadteTime() {
		return this.upadteTime;
	}

	public void setUpadteTime(Date upadteTime) {
		this.upadteTime = upadteTime;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
