package net.fantesy84.sys.solution.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpSysAcctSltRels generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_ACCT_SLT_RELS", catalog = "EASY_PAY")
public class EpSysAcctSltRels implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1375281240519660688L;
	private EpSysAcctSltRelsId id;
	private EpSysSolution epSysSolution;
	private boolean deleteFlag;
	private Date createTime;
	private Date updateTime;

	public EpSysAcctSltRels() {
	}

	public EpSysAcctSltRels(EpSysAcctSltRelsId id, EpSysSolution epSysSolution, boolean deleteFlag, Date createTime) {
		this.id = id;
		this.epSysSolution = epSysSolution;
		this.deleteFlag = deleteFlag;
		this.createTime = createTime;
	}

	public EpSysAcctSltRels(EpSysAcctSltRelsId id, EpSysSolution epSysSolution, boolean deleteFlag, Date createTime,
			Date updateTime) {
		this.id = id;
		this.epSysSolution = epSysSolution;
		this.deleteFlag = deleteFlag;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "refId", column = @Column(name = "REF_ID", nullable = false)),
			@AttributeOverride(name = "sltId", column = @Column(name = "SLT_ID", nullable = false)),
			@AttributeOverride(name = "refLevel", column = @Column(name = "REF_LEVEL", nullable = false, length = 12)) })
	public EpSysAcctSltRelsId getId() {
		return this.id;
	}

	public void setId(EpSysAcctSltRelsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SLT_ID", nullable = false, insertable = false, updatable = false)
	public EpSysSolution getEpSysSolution() {
		return this.epSysSolution;
	}

	public void setEpSysSolution(EpSysSolution epSysSolution) {
		this.epSysSolution = epSysSolution;
	}

	@Column(name = "DELETE_FLAG", nullable = false)
	public boolean isDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
