package net.fantesy84.sys.solution.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EpSysAcctSltRelsId generated by hbm2java
 */
@Embeddable
public class EpSysAcctSltRelsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5608457598135484121L;
	private int refId;
	private int sltId;
	private String refLevel;

	public EpSysAcctSltRelsId() {
	}

	public EpSysAcctSltRelsId(int refId, int sltId, String refLevel) {
		this.refId = refId;
		this.sltId = sltId;
		this.refLevel = refLevel;
	}

	@Column(name = "REF_ID", nullable = false)
	public int getRefId() {
		return this.refId;
	}

	public void setRefId(int refId) {
		this.refId = refId;
	}

	@Column(name = "SLT_ID", nullable = false)
	public int getSltId() {
		return this.sltId;
	}

	public void setSltId(int sltId) {
		this.sltId = sltId;
	}

	@Column(name = "REF_LEVEL", nullable = false, length = 12)
	public String getRefLevel() {
		return this.refLevel;
	}

	public void setRefLevel(String refLevel) {
		this.refLevel = refLevel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EpSysAcctSltRelsId))
			return false;
		EpSysAcctSltRelsId castOther = (EpSysAcctSltRelsId) other;

		return (this.getRefId() == castOther.getRefId()) && (this.getSltId() == castOther.getSltId())
				&& ((this.getRefLevel() == castOther.getRefLevel()) || (this.getRefLevel() != null
						&& castOther.getRefLevel() != null && this.getRefLevel().equals(castOther.getRefLevel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRefId();
		result = 37 * result + this.getSltId();
		result = 37 * result + (getRefLevel() == null ? 0 : this.getRefLevel().hashCode());
		return result;
	}

}
