package net.fantesy84.sys.solution.domain;
// Generated 2016-4-13 22:00:27 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EpSysSolutionBankFee generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_SOLUTION_BANK_FEE", catalog = "EASY_PAY")
public class EpSysSolutionBankFee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2453391029299857357L;
	private Integer autoId;
	private RpSysSolution rpSysSolution;
	private BigDecimal feeAmount;
	private boolean isGlobal;
	private boolean deleteFlag;

	public EpSysSolutionBankFee() {
	}

	public EpSysSolutionBankFee(RpSysSolution rpSysSolution, BigDecimal feeAmount, boolean isGlobal,
			boolean deleteFlag) {
		this.rpSysSolution = rpSysSolution;
		this.feeAmount = feeAmount;
		this.isGlobal = isGlobal;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SLT_ID", nullable = false)
	public RpSysSolution getRpSysSolution() {
		return this.rpSysSolution;
	}

	public void setRpSysSolution(RpSysSolution rpSysSolution) {
		this.rpSysSolution = rpSysSolution;
	}

	@Column(name = "FEE_AMOUNT", nullable = false, precision = 18)
	public BigDecimal getFeeAmount() {
		return this.feeAmount;
	}

	public void setFeeAmount(BigDecimal feeAmount) {
		this.feeAmount = feeAmount;
	}

	@Column(name = "IS_GLOBAL", nullable = false)
	public boolean isIsGlobal() {
		return this.isGlobal;
	}

	public void setIsGlobal(boolean isGlobal) {
		this.isGlobal = isGlobal;
	}

	@Column(name = "DELETE_FLAG", nullable = false)
	public boolean isDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
