package net.fantesy84.sys.solution.domain;
// Generated 2016-4-13 22:00:27 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RpSysAcctSltRelsId generated by hbm2java
 */
@Embeddable
public class RpSysAcctSltRelsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7803005082453927829L;
	private int sltId;
	private int acctId;

	public RpSysAcctSltRelsId() {
	}

	public RpSysAcctSltRelsId(int sltId, int acctId) {
		this.sltId = sltId;
		this.acctId = acctId;
	}

	@Column(name = "SLT_ID", nullable = false)
	public int getSltId() {
		return this.sltId;
	}

	public void setSltId(int sltId) {
		this.sltId = sltId;
	}

	@Column(name = "ACCT_ID", nullable = false)
	public int getAcctId() {
		return this.acctId;
	}

	public void setAcctId(int acctId) {
		this.acctId = acctId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RpSysAcctSltRelsId))
			return false;
		RpSysAcctSltRelsId castOther = (RpSysAcctSltRelsId) other;

		return (this.getSltId() == castOther.getSltId()) && (this.getAcctId() == castOther.getAcctId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSltId();
		result = 37 * result + this.getAcctId();
		return result;
	}

}
