package net.fantesy84.sys.solution.domain;
// Generated 2016-4-13 22:00:27 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * RpSysSolutionAcctGaings generated by hbm2java
 */
@Entity
@Table(name = "RP_SYS_SOLUTION_ACCT_GAINGS", catalog = "EASY_PAY")
public class RpSysSolutionAcctGaings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -49583620891029981L;
	private Integer autoId;
	private int version;
	private RpSysSolution rpSysSolution;
	private String formula;
	private BigDecimal gainsAmount;
	private boolean isGlobal;

	public RpSysSolutionAcctGaings() {
	}

	public RpSysSolutionAcctGaings(RpSysSolution rpSysSolution, String formula, BigDecimal gainsAmount,
			boolean isGlobal) {
		this.rpSysSolution = rpSysSolution;
		this.formula = formula;
		this.gainsAmount = gainsAmount;
		this.isGlobal = isGlobal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@Version
	@Column(name = "VERSION", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SLT_ID", nullable = false)
	public RpSysSolution getRpSysSolution() {
		return this.rpSysSolution;
	}

	public void setRpSysSolution(RpSysSolution rpSysSolution) {
		this.rpSysSolution = rpSysSolution;
	}

	@Column(name = "FORMULA", nullable = false, length = 500)
	public String getFormula() {
		return this.formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	@Column(name = "GAINS_AMOUNT", nullable = false, precision = 15)
	public BigDecimal getGainsAmount() {
		return this.gainsAmount;
	}

	public void setGainsAmount(BigDecimal gainsAmount) {
		this.gainsAmount = gainsAmount;
	}

	@Column(name = "IS_GLOBAL", nullable = false)
	public boolean isIsGlobal() {
		return this.isGlobal;
	}

	public void setIsGlobal(boolean isGlobal) {
		this.isGlobal = isGlobal;
	}

}
