package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * EpQuartzBlobTriggers generated by hbm2java
 */
@Entity
@Table(name = "EP_QUARTZ_BLOB_TRIGGERS", catalog = "EASY_PAY")
public class EpQuartzBlobTriggers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6165793755027705399L;
	private EpQuartzBlobTriggersId id;
	private EpQuartzTriggers epQuartzTriggers;
	private byte[] blobData;

	public EpQuartzBlobTriggers() {
	}

	public EpQuartzBlobTriggers(EpQuartzTriggers epQuartzTriggers) {
		this.epQuartzTriggers = epQuartzTriggers;
	}

	public EpQuartzBlobTriggers(EpQuartzTriggers epQuartzTriggers, byte[] blobData) {
		this.epQuartzTriggers = epQuartzTriggers;
		this.blobData = blobData;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerName", column = @Column(name = "TRIGGER_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public EpQuartzBlobTriggersId getId() {
		return this.id;
	}

	public void setId(EpQuartzBlobTriggersId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public EpQuartzTriggers getEpQuartzTriggers() {
		return this.epQuartzTriggers;
	}

	public void setEpQuartzTriggers(EpQuartzTriggers epQuartzTriggers) {
		this.epQuartzTriggers = epQuartzTriggers;
	}

	@Column(name = "BLOB_DATA")
	public byte[] getBlobData() {
		return this.blobData;
	}

	public void setBlobData(byte[] blobData) {
		this.blobData = blobData;
	}

}
