package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EpQuartzPausedTriggerGrps generated by hbm2java
 */
@Entity
@Table(name = "EP_QUARTZ_PAUSED_TRIGGER_GRPS", catalog = "EASY_PAY")
public class EpQuartzPausedTriggerGrps implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5872001293723621966L;
	private EpQuartzPausedTriggerGrpsId id;

	public EpQuartzPausedTriggerGrps() {
	}

	public EpQuartzPausedTriggerGrps(EpQuartzPausedTriggerGrpsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public EpQuartzPausedTriggerGrpsId getId() {
		return this.id;
	}

	public void setId(EpQuartzPausedTriggerGrpsId id) {
		this.id = id;
	}

}
