package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * EpQuartzCronTriggers generated by hbm2java
 */
@Entity
@Table(name = "EP_QUARTZ_CRON_TRIGGERS", catalog = "EASY_PAY")
public class EpQuartzCronTriggers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3400104310987373312L;
	private EpQuartzCronTriggersId id;
	private EpQuartzTriggers epQuartzTriggers;
	private String cronExpression;
	private String timeZoneId;

	public EpQuartzCronTriggers() {
	}

	public EpQuartzCronTriggers(EpQuartzTriggers epQuartzTriggers, String cronExpression) {
		this.epQuartzTriggers = epQuartzTriggers;
		this.cronExpression = cronExpression;
	}

	public EpQuartzCronTriggers(EpQuartzTriggers epQuartzTriggers, String cronExpression, String timeZoneId) {
		this.epQuartzTriggers = epQuartzTriggers;
		this.cronExpression = cronExpression;
		this.timeZoneId = timeZoneId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerName", column = @Column(name = "TRIGGER_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public EpQuartzCronTriggersId getId() {
		return this.id;
	}

	public void setId(EpQuartzCronTriggersId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public EpQuartzTriggers getEpQuartzTriggers() {
		return this.epQuartzTriggers;
	}

	public void setEpQuartzTriggers(EpQuartzTriggers epQuartzTriggers) {
		this.epQuartzTriggers = epQuartzTriggers;
	}

	@Column(name = "CRON_EXPRESSION", nullable = false, length = 120)
	public String getCronExpression() {
		return this.cronExpression;
	}

	public void setCronExpression(String cronExpression) {
		this.cronExpression = cronExpression;
	}

	@Column(name = "TIME_ZONE_ID", length = 80)
	public String getTimeZoneId() {
		return this.timeZoneId;
	}

	public void setTimeZoneId(String timeZoneId) {
		this.timeZoneId = timeZoneId;
	}

}
