package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EpQuartzCalendars generated by hbm2java
 */
@Entity
@Table(name = "EP_QUARTZ_CALENDARS", catalog = "EASY_PAY")
public class EpQuartzCalendars implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6421917047792561559L;
	private EpQuartzCalendarsId id;
	private byte[] calendar;

	public EpQuartzCalendars() {
	}

	public EpQuartzCalendars(EpQuartzCalendarsId id, byte[] calendar) {
		this.id = id;
		this.calendar = calendar;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "calendarName", column = @Column(name = "CALENDAR_NAME", nullable = false, length = 200)) })
	public EpQuartzCalendarsId getId() {
		return this.id;
	}

	public void setId(EpQuartzCalendarsId id) {
		this.id = id;
	}

	@Column(name = "CALENDAR", nullable = false)
	public byte[] getCalendar() {
		return this.calendar;
	}

	public void setCalendar(byte[] calendar) {
		this.calendar = calendar;
	}

}
