package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EpQuartzBlobTriggersId generated by hbm2java
 */
@Embeddable
public class EpQuartzBlobTriggersId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6787438073996843947L;
	private String schedName;
	private String triggerName;
	private String triggerGroup;

	public EpQuartzBlobTriggersId() {
	}

	public EpQuartzBlobTriggersId(String schedName, String triggerName, String triggerGroup) {
		this.schedName = schedName;
		this.triggerName = triggerName;
		this.triggerGroup = triggerGroup;
	}

	@Column(name = "SCHED_NAME", nullable = false, length = 120)
	public String getSchedName() {
		return this.schedName;
	}

	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	@Column(name = "TRIGGER_NAME", nullable = false, length = 200)
	public String getTriggerName() {
		return this.triggerName;
	}

	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}

	@Column(name = "TRIGGER_GROUP", nullable = false, length = 200)
	public String getTriggerGroup() {
		return this.triggerGroup;
	}

	public void setTriggerGroup(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EpQuartzBlobTriggersId))
			return false;
		EpQuartzBlobTriggersId castOther = (EpQuartzBlobTriggersId) other;

		return ((this.getSchedName() == castOther.getSchedName()) || (this.getSchedName() != null
				&& castOther.getSchedName() != null && this.getSchedName().equals(castOther.getSchedName())))
				&& ((this.getTriggerName() == castOther.getTriggerName())
						|| (this.getTriggerName() != null && castOther.getTriggerName() != null
								&& this.getTriggerName().equals(castOther.getTriggerName())))
				&& ((this.getTriggerGroup() == castOther.getTriggerGroup())
						|| (this.getTriggerGroup() != null && castOther.getTriggerGroup() != null
								&& this.getTriggerGroup().equals(castOther.getTriggerGroup())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSchedName() == null ? 0 : this.getSchedName().hashCode());
		result = 37 * result + (getTriggerName() == null ? 0 : this.getTriggerName().hashCode());
		result = 37 * result + (getTriggerGroup() == null ? 0 : this.getTriggerGroup().hashCode());
		return result;
	}

}
