package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * EpQuartzSimpleTriggers generated by hbm2java
 */
@Entity
@Table(name = "EP_QUARTZ_SIMPLE_TRIGGERS", catalog = "EASY_PAY")
public class EpQuartzSimpleTriggers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7188391736269298399L;
	private EpQuartzSimpleTriggersId id;
	private EpQuartzTriggers epQuartzTriggers;
	private long repeatCount;
	private long repeatInterval;
	private long timesTriggered;

	public EpQuartzSimpleTriggers() {
	}

	public EpQuartzSimpleTriggers(EpQuartzTriggers epQuartzTriggers, long repeatCount, long repeatInterval,
			long timesTriggered) {
		this.epQuartzTriggers = epQuartzTriggers;
		this.repeatCount = repeatCount;
		this.repeatInterval = repeatInterval;
		this.timesTriggered = timesTriggered;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "triggerName", column = @Column(name = "TRIGGER_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public EpQuartzSimpleTriggersId getId() {
		return this.id;
	}

	public void setId(EpQuartzSimpleTriggersId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public EpQuartzTriggers getEpQuartzTriggers() {
		return this.epQuartzTriggers;
	}

	public void setEpQuartzTriggers(EpQuartzTriggers epQuartzTriggers) {
		this.epQuartzTriggers = epQuartzTriggers;
	}

	@Column(name = "REPEAT_COUNT", nullable = false)
	public long getRepeatCount() {
		return this.repeatCount;
	}

	public void setRepeatCount(long repeatCount) {
		this.repeatCount = repeatCount;
	}

	@Column(name = "REPEAT_INTERVAL", nullable = false)
	public long getRepeatInterval() {
		return this.repeatInterval;
	}

	public void setRepeatInterval(long repeatInterval) {
		this.repeatInterval = repeatInterval;
	}

	@Column(name = "TIMES_TRIGGERED", nullable = false)
	public long getTimesTriggered() {
		return this.timesTriggered;
	}

	public void setTimesTriggered(long timesTriggered) {
		this.timesTriggered = timesTriggered;
	}

}
