package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EpQuartzFiredTriggersId generated by hbm2java
 */
@Embeddable
public class EpQuartzFiredTriggersId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5210376866308769663L;
	private String schedName;
	private String entryId;

	public EpQuartzFiredTriggersId() {
	}

	public EpQuartzFiredTriggersId(String schedName, String entryId) {
		this.schedName = schedName;
		this.entryId = entryId;
	}

	@Column(name = "SCHED_NAME", nullable = false, length = 120)
	public String getSchedName() {
		return this.schedName;
	}

	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	@Column(name = "ENTRY_ID", nullable = false, length = 95)
	public String getEntryId() {
		return this.entryId;
	}

	public void setEntryId(String entryId) {
		this.entryId = entryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EpQuartzFiredTriggersId))
			return false;
		EpQuartzFiredTriggersId castOther = (EpQuartzFiredTriggersId) other;

		return ((this.getSchedName() == castOther.getSchedName()) || (this.getSchedName() != null
				&& castOther.getSchedName() != null && this.getSchedName().equals(castOther.getSchedName())))
				&& ((this.getEntryId() == castOther.getEntryId()) || (this.getEntryId() != null
						&& castOther.getEntryId() != null && this.getEntryId().equals(castOther.getEntryId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSchedName() == null ? 0 : this.getSchedName().hashCode());
		result = 37 * result + (getEntryId() == null ? 0 : this.getEntryId().hashCode());
		return result;
	}

}
