package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EpQuartzLocks generated by hbm2java
 */
@Entity
@Table(name = "EP_QUARTZ_LOCKS", catalog = "EASY_PAY")
public class EpQuartzLocks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2462006719711973255L;
	private EpQuartzLocksId id;

	public EpQuartzLocks() {
	}

	public EpQuartzLocks(EpQuartzLocksId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "lockName", column = @Column(name = "LOCK_NAME", nullable = false, length = 40)) })
	public EpQuartzLocksId getId() {
		return this.id;
	}

	public void setId(EpQuartzLocksId id) {
		this.id = id;
	}

}
