package net.fantesy84.quartz.domain;
// Generated 2016-4-26 23:18:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EpQuartzSchedulerState generated by hbm2java
 */
@Entity
@Table(name = "EP_QUARTZ_SCHEDULER_STATE", catalog = "EASY_PAY")
public class EpQuartzSchedulerState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7130088828286293011L;
	private EpQuartzSchedulerStateId id;
	private long lastCheckinTime;
	private long checkinInterval;

	public EpQuartzSchedulerState() {
	}

	public EpQuartzSchedulerState(EpQuartzSchedulerStateId id, long lastCheckinTime, long checkinInterval) {
		this.id = id;
		this.lastCheckinTime = lastCheckinTime;
		this.checkinInterval = checkinInterval;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "schedName", column = @Column(name = "SCHED_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "instanceName", column = @Column(name = "INSTANCE_NAME", nullable = false, length = 200)) })
	public EpQuartzSchedulerStateId getId() {
		return this.id;
	}

	public void setId(EpQuartzSchedulerStateId id) {
		this.id = id;
	}

	@Column(name = "LAST_CHECKIN_TIME", nullable = false)
	public long getLastCheckinTime() {
		return this.lastCheckinTime;
	}

	public void setLastCheckinTime(long lastCheckinTime) {
		this.lastCheckinTime = lastCheckinTime;
	}

	@Column(name = "CHECKIN_INTERVAL", nullable = false)
	public long getCheckinInterval() {
		return this.checkinInterval;
	}

	public void setCheckinInterval(long checkinInterval) {
		this.checkinInterval = checkinInterval;
	}

}
