package net.fantesy84.sys.bank.domain;
// Generated 2016-4-13 22:00:27 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import net.fantesy84.sys.customer.domain.EpSysAccount;

/**
 * EpSysBankOrder generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_BANK_ORDER", catalog = "EASY_PAY")
public class EpSysBankOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -492627923684479705L;
	private Integer autoId;
	private EpSysAccount epSysAccount;
	private String backName;
	private BigDecimal amount;
	private Boolean deleteFlag;

	public EpSysBankOrder() {
	}

	public EpSysBankOrder(EpSysAccount epSysAccount, String backName, BigDecimal amount) {
		this.epSysAccount = epSysAccount;
		this.backName = backName;
		this.amount = amount;
	}

	public EpSysBankOrder(EpSysAccount epSysAccount, String backName, BigDecimal amount, Boolean deleteFlag) {
		this.epSysAccount = epSysAccount;
		this.backName = backName;
		this.amount = amount;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCT_ID", nullable = false)
	public EpSysAccount getEpSysAccount() {
		return this.epSysAccount;
	}

	public void setEpSysAccount(EpSysAccount epSysAccount) {
		this.epSysAccount = epSysAccount;
	}

	@Column(name = "BACK_NAME", nullable = false, length = 80)
	public String getBackName() {
		return this.backName;
	}

	public void setBackName(String backName) {
		this.backName = backName;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 20)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
