package net.fantesy84.sys.dictionary.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EpSysDictItem generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_DICT_ITEM", catalog = "EASY_PAY")
public class EpSysDictItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 630948413748642721L;
	private Integer autoId;
	private EpSysDict epSysDict;
	private String itemCode;
	private String itemValue;
	private String itemDesc;
	private Integer sort;

	public EpSysDictItem() {
	}

	public EpSysDictItem(EpSysDict epSysDict, String itemCode, String itemValue) {
		this.epSysDict = epSysDict;
		this.itemCode = itemCode;
		this.itemValue = itemValue;
	}

	public EpSysDictItem(EpSysDict epSysDict, String itemCode, String itemValue, String itemDesc, Integer sort) {
		this.epSysDict = epSysDict;
		this.itemCode = itemCode;
		this.itemValue = itemValue;
		this.itemDesc = itemDesc;
		this.sort = sort;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DICT_ID", nullable = false)
	public EpSysDict getEpSysDict() {
		return this.epSysDict;
	}

	public void setEpSysDict(EpSysDict epSysDict) {
		this.epSysDict = epSysDict;
	}

	@Column(name = "ITEM_CODE", nullable = false, length = 100)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "ITEM_VALUE", nullable = false, length = 120)
	public String getItemValue() {
		return this.itemValue;
	}

	public void setItemValue(String itemValue) {
		this.itemValue = itemValue;
	}

	@Column(name = "ITEM_DESC", length = 800)
	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	@Column(name = "SORT")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

}
