package net.fantesy84.sys.bill.domain;
// Generated 2016-4-13 22:00:27 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import net.fantesy84.sys.customer.domain.EpSysAccount;

/**
 * EpSysBill generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_BILL", catalog = "EASY_PAY")
public class EpSysBill implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4884217461399617451L;
	private Integer autoId;
	private EpSysAccount epSysAccount;
	private BigDecimal billAmount;
	private Boolean deleteFlag;

	public EpSysBill() {
	}

	public EpSysBill(EpSysAccount epSysAccount, BigDecimal billAmount) {
		this.epSysAccount = epSysAccount;
		this.billAmount = billAmount;
	}

	public EpSysBill(EpSysAccount epSysAccount, BigDecimal billAmount, Boolean deleteFlag) {
		this.epSysAccount = epSysAccount;
		this.billAmount = billAmount;
		this.deleteFlag = deleteFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCT_ID", nullable = false)
	public EpSysAccount getEpSysAccount() {
		return this.epSysAccount;
	}

	public void setEpSysAccount(EpSysAccount epSysAccount) {
		this.epSysAccount = epSysAccount;
	}

	@Column(name = "BILL_AMOUNT", nullable = false, precision = 20)
	public BigDecimal getBillAmount() {
		return this.billAmount;
	}

	public void setBillAmount(BigDecimal billAmount) {
		this.billAmount = billAmount;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
