package net.fantesy84.sys.account.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpSysAcctProLine generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_ACCT_PRO_LINE", catalog = "EASY_PAY")
public class EpSysAcctProLine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9011192218176180971L;
	private Integer autoId;
	private String aplName;
	private String aplDesc;
	private Boolean deleteFlag;
	private Date createTime;
	private Date updateTime;
	private Set<EpSysAcctProduct> epSysAcctProducts = new HashSet<EpSysAcctProduct>(0);

	public EpSysAcctProLine() {
	}

	public EpSysAcctProLine(String aplName, Date createTime, Date updateTime) {
		this.aplName = aplName;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public EpSysAcctProLine(String aplName, String aplDesc, Boolean deleteFlag, Date createTime, Date updateTime,
			Set<EpSysAcctProduct> epSysAcctProducts) {
		this.aplName = aplName;
		this.aplDesc = aplDesc;
		this.deleteFlag = deleteFlag;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.epSysAcctProducts = epSysAcctProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@Column(name = "APL_NAME", nullable = false, length = 120)
	public String getAplName() {
		return this.aplName;
	}

	public void setAplName(String aplName) {
		this.aplName = aplName;
	}

	@Column(name = "APL_DESC", length = 65535)
	public String getAplDesc() {
		return this.aplDesc;
	}

	public void setAplDesc(String aplDesc) {
		this.aplDesc = aplDesc;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "epSysAcctProLine")
	public Set<EpSysAcctProduct> getEpSysAcctProducts() {
		return this.epSysAcctProducts;
	}

	public void setEpSysAcctProducts(Set<EpSysAcctProduct> epSysAcctProducts) {
		this.epSysAcctProducts = epSysAcctProducts;
	}

}
