package net.fantesy84.sys.account.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import net.fantesy84.sys.user.domain.EpSysUser;

/**
 * EpSysAccount generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_ACCOUNT", catalog = "EASY_PAY")
public class EpSysAccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9125185553208797000L;
	private Integer autoId;
	private EpSysAcctProduct epSysAcctProduct;
	private EpSysUser epSysUser;
	private String acctName;
	private String acctNum;
	private String currencyType;
	private BigDecimal acctBalance;
	private Boolean deleteFlag;
	private Date createTime;
	private Date updateTime;

	public EpSysAccount() {
	}

	public EpSysAccount(EpSysAcctProduct epSysAcctProduct, EpSysUser epSysUser, String acctName, String acctNum,
			String currencyType, BigDecimal acctBalance, Date createTime) {
		this.epSysAcctProduct = epSysAcctProduct;
		this.epSysUser = epSysUser;
		this.acctName = acctName;
		this.acctNum = acctNum;
		this.currencyType = currencyType;
		this.acctBalance = acctBalance;
		this.createTime = createTime;
	}

	public EpSysAccount(EpSysAcctProduct epSysAcctProduct, EpSysUser epSysUser, String acctName, String acctNum,
			String currencyType, BigDecimal acctBalance, Boolean deleteFlag, Date createTime, Date updateTime) {
		this.epSysAcctProduct = epSysAcctProduct;
		this.epSysUser = epSysUser;
		this.acctName = acctName;
		this.acctNum = acctNum;
		this.currencyType = currencyType;
		this.acctBalance = acctBalance;
		this.deleteFlag = deleteFlag;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AP_ID", nullable = false)
	public EpSysAcctProduct getEpSysAcctProduct() {
		return this.epSysAcctProduct;
	}

	public void setEpSysAcctProduct(EpSysAcctProduct epSysAcctProduct) {
		this.epSysAcctProduct = epSysAcctProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public EpSysUser getEpSysUser() {
		return this.epSysUser;
	}

	public void setEpSysUser(EpSysUser epSysUser) {
		this.epSysUser = epSysUser;
	}

	@Column(name = "ACCT_NAME", nullable = false, length = 120)
	public String getAcctName() {
		return this.acctName;
	}

	public void setAcctName(String acctName) {
		this.acctName = acctName;
	}

	@Column(name = "ACCT_NUM", nullable = false, length = 20)
	public String getAcctNum() {
		return this.acctNum;
	}

	public void setAcctNum(String acctNum) {
		this.acctNum = acctNum;
	}

	@Column(name = "CURRENCY_TYPE", nullable = false, length = 7)
	public String getCurrencyType() {
		return this.currencyType;
	}

	public void setCurrencyType(String currencyType) {
		this.currencyType = currencyType;
	}

	@Column(name = "ACCT_BALANCE", nullable = false, precision = 20)
	public BigDecimal getAcctBalance() {
		return this.acctBalance;
	}

	public void setAcctBalance(BigDecimal acctBalance) {
		this.acctBalance = acctBalance;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
