package net.fantesy84.sys.order.domain;
// Generated 2016-4-26 23:25:28 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpSysMainOrder generated by hbm2java
 */
@Entity
@Table(name = "EP_SYS_MAIN_ORDER", catalog = "EASY_PAY")
public class EpSysMainOrder implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -355209463052981562L;
	private Integer autoId;
	private int acctId;
	private BigDecimal billAmount;
	private Boolean deleteFlag;
	private Date createTime;
	private Date updateTime;

	public EpSysMainOrder() {
	}

	public EpSysMainOrder(int acctId, BigDecimal billAmount, Date createTime) {
		this.acctId = acctId;
		this.billAmount = billAmount;
		this.createTime = createTime;
	}

	public EpSysMainOrder(int acctId, BigDecimal billAmount, Boolean deleteFlag, Date createTime, Date updateTime) {
		this.acctId = acctId;
		this.billAmount = billAmount;
		this.deleteFlag = deleteFlag;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUTO_ID", unique = true, nullable = false)
	public Integer getAutoId() {
		return this.autoId;
	}

	public void setAutoId(Integer autoId) {
		this.autoId = autoId;
	}

	@Column(name = "ACCT_ID", nullable = false)
	public int getAcctId() {
		return this.acctId;
	}

	public void setAcctId(int acctId) {
		this.acctId = acctId;
	}

	@Column(name = "BILL_AMOUNT", nullable = false, precision = 20)
	public BigDecimal getBillAmount() {
		return this.billAmount;
	}

	public void setBillAmount(BigDecimal billAmount) {
		this.billAmount = billAmount;
	}

	@Column(name = "DELETE_FLAG")
	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
