/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.6.29 : Database - EASY_PAY
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`EASY_PAY` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

/*Table structure for table `EP_SYS_ACCOUNT` */

CREATE TABLE `EP_SYS_ACCOUNT` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(10) unsigned NOT NULL,
  `ACCT_NUM` int(20) NOT NULL,
  `ACCT_TYPE` char(2) NOT NULL COMMENT '00为境内账户,01为境外账户',
  `ACCT_BALANCE` decimal(20,2) NOT NULL,
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_ACCOUNT_USER_ID` (`USER_ID`),
  CONSTRAINT `FK_ACCOUNT_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `EP_SYS_USER` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_BANK_ORDER` */

CREATE TABLE `EP_SYS_BANK_ORDER` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ACCT_ID` int(10) unsigned NOT NULL,
  `BACK_NAME` varchar(80) NOT NULL,
  `AMOUNT` decimal(20,2) NOT NULL,
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_BACK_ACCT_ID` (`ACCT_ID`),
  CONSTRAINT `FK_BACK_ACCT_ID` FOREIGN KEY (`ACCT_ID`) REFERENCES `EP_SYS_ACCOUNT` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_BILL` */

CREATE TABLE `EP_SYS_BILL` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ACCT_ID` int(10) unsigned NOT NULL,
  `BILL_AMOUNT` decimal(20,2) NOT NULL,
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_BILL_ACCOUNT_ID` (`ACCT_ID`),
  CONSTRAINT `FK_BILL_ACCOUNT_ID` FOREIGN KEY (`ACCT_ID`) REFERENCES `EP_SYS_ACCOUNT` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_CUST` */

CREATE TABLE `EP_SYS_CUST` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CUST_NAME` varchar(40) NOT NULL,
  `IS_CORP_CUST` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否企业客户,0为false,1为true',
  PRIMARY KEY (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_SOLUTION_BANK_FEE` */

CREATE TABLE `EP_SYS_SOLUTION_BANK_FEE` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `SLT_ID` int(10) unsigned NOT NULL,
  `FEE_AMOUNT` decimal(18,2) NOT NULL,
  `IS_GLOBAL` tinyint(1) NOT NULL DEFAULT '0',
  `DELETE_FLAG` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_BANKFEE_SLT_ID` (`SLT_ID`),
  CONSTRAINT `FK_BANKFEE_SLT_ID` FOREIGN KEY (`SLT_ID`) REFERENCES `RP_SYS_SOLUTION` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_USER` */

CREATE TABLE `EP_SYS_USER` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CUST_ID` int(10) unsigned NOT NULL,
  `USERNAME` varchar(40) NOT NULL,
  `PASSWD` varchar(160) NOT NULL,
  `REAL_NAME` varchar(60) NOT NULL,
  `DELETE_FLAG` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_USER_CUST_ID` (`CUST_ID`),
  CONSTRAINT `FK_USER_CUST_ID` FOREIGN KEY (`CUST_ID`) REFERENCES `EP_SYS_CUST` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `RP_SYS_ACCT_SLT_RELS` */

CREATE TABLE `RP_SYS_ACCT_SLT_RELS` (
  `ACCT_ID` int(10) unsigned NOT NULL,
  `SLT_ID` int(10) unsigned NOT NULL,
  `DELETE_FLAG` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`SLT_ID`,`ACCT_ID`),
  KEY `FK_REL_ACCT_ID` (`ACCT_ID`),
  CONSTRAINT `FK_REL_ACCT_ID` FOREIGN KEY (`ACCT_ID`) REFERENCES `EP_SYS_ACCOUNT` (`AUTO_ID`),
  CONSTRAINT `FK_REL_SLT_ID` FOREIGN KEY (`SLT_ID`) REFERENCES `RP_SYS_SOLUTION` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `RP_SYS_SOLUTION` */

CREATE TABLE `RP_SYS_SOLUTION` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `SLT_NAME` varchar(20) NOT NULL,
  `SLT_TYPE` varchar(10) NOT NULL,
  `BIZ_TYPE` varchar(20) NOT NULL COMMENT '业务类型,用于确定子表',
  `DELETE_FLAG` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='方案表(产品线表)';

/*Table structure for table `RP_SYS_SOLUTION_ACCT_GAINGS` */

CREATE TABLE `RP_SYS_SOLUTION_ACCT_GAINGS` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `SLT_ID` int(10) unsigned NOT NULL,
  `FORMULA` varchar(500) NOT NULL,
  `GAINS_AMOUNT` decimal(15,2) NOT NULL,
  `IS_GLOBAL` tinyint(1) NOT NULL DEFAULT '0',
  `VERSION` int(3) NOT NULL,
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_DTL_SLT_ID` (`SLT_ID`),
  CONSTRAINT `FK_DTL_SLT_ID` FOREIGN KEY (`SLT_ID`) REFERENCES `RP_SYS_SOLUTION` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账户收益方案(产品线)';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
