/*
SQLyog Ultimate v12.09 (64 bit)
MySQL - 5.5.47-MariaDB : Database - EASY_PAY
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`EASY_PAY` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `EASY_PAY`;

/*Table structure for table `EP_SYS_ACCOUNT` */

CREATE TABLE `EP_SYS_ACCOUNT` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(10) unsigned NOT NULL COMMENT '用户ID',
  `AP_ID` int(10) unsigned NOT NULL COMMENT '账户产品ID',
  `ACCT_NAME` varchar(120) NOT NULL,
  `ACCT_NUM` varchar(20) NOT NULL COMMENT '账户号',
  `CURRENCY_TYPE` char(7) NOT NULL DEFAULT 'CRC_000' COMMENT '货币类型',
  `ACCT_BALANCE` decimal(20,2) NOT NULL COMMENT '账户余额',
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_ACCOUNT_USER_ID` (`USER_ID`),
  KEY `FK_EP_SYS_ACCOUNT_EP_SYS_ACCT_PRODUCT1_idx` (`AP_ID`),
  CONSTRAINT `FK_EP_SYS_ACCOUNT_EP_SYS_ACCT_PRODUCT1` FOREIGN KEY (`AP_ID`) REFERENCES `EP_SYS_ACCT_PRODUCT` (`AUTO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_EP_SYS_ACCOUNT_EP_SYS_USER1` FOREIGN KEY (`USER_ID`) REFERENCES `EP_SYS_USER` (`AUTO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

/*Table structure for table `EP_SYS_ACCT_PRO_LINE` */

CREATE TABLE `EP_SYS_ACCT_PRO_LINE` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `APL_NAME` varchar(120) NOT NULL,
  `APL_DESC` text,
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Table structure for table `EP_SYS_ACCT_PRODUCT` */

CREATE TABLE `EP_SYS_ACCT_PRODUCT` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `APL_ID` int(10) unsigned NOT NULL,
  `AP_NAME` varchar(80) NOT NULL COMMENT '账户产品名称',
  `AP_BIZ` varchar(80) NOT NULL COMMENT '账户产品业务类型',
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_APL_ID` (`APL_ID`),
  CONSTRAINT `FK_APL_ID` FOREIGN KEY (`APL_ID`) REFERENCES `EP_SYS_ACCT_PRO_LINE` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Table structure for table `EP_SYS_ACCT_SLT_RELS` */

CREATE TABLE `EP_SYS_ACCT_SLT_RELS` (
  `REF_ID` int(10) unsigned NOT NULL COMMENT '引用的ID,可能为账户,账户产品,账户产品线其中一种表的ID',
  `REF_LEVEL` enum('ACCOUNT','PRODUCT','PRODUCT_LINE') NOT NULL DEFAULT 'ACCOUNT' COMMENT '引用ID级别: ACCOUNT为账户,PRODUCT为账户产品,PRODUCT_LINE为账户产品线',
  `SLT_ID` int(10) unsigned NOT NULL COMMENT '引用方案ID',
  `DELETE_FLAG` tinyint(1) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `CREATE_TIME` datetime NOT NULL COMMENT '更新时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '删除标记',
  PRIMARY KEY (`REF_ID`,`SLT_ID`,`REF_LEVEL`),
  KEY `FK_REL_ACCT_ID` (`REF_ID`),
  KEY `FK_SOLUTION_ID_idx` (`SLT_ID`),
  CONSTRAINT `FK_SOLUTION_ID` FOREIGN KEY (`SLT_ID`) REFERENCES `EP_SYS_SOLUTION` (`AUTO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_CUST` */

CREATE TABLE `EP_SYS_CUST` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CUST_NAME` varchar(40) NOT NULL,
  `CUST_TYPE` enum('CORPORATION','PERSONAL','GOVERNMENT') NOT NULL COMMENT 'CORPORATION为企业客户,PERSONAL为个人客户,GOVERNMENT为政府客户',
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_DICT` */

CREATE TABLE `EP_SYS_DICT` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DICT_CODE` varchar(100) NOT NULL,
  `DICT_NAME` varchar(200) NOT NULL,
  `DICT_DESC` varchar(800) DEFAULT '',
  `SORT` int(3) DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `IDX_DICT_CODE` (`DICT_CODE`),
  KEY `IDX_DICT_SORT` (`AUTO_ID`,`SORT`,`DICT_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

/*Table structure for table `EP_SYS_DICT_ITEM` */

CREATE TABLE `EP_SYS_DICT_ITEM` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DICT_ID` int(10) unsigned NOT NULL,
  `ITEM_CODE` varchar(100) NOT NULL,
  `ITEM_VALUE` varchar(120) NOT NULL,
  `ITEM_DESC` varchar(800) DEFAULT '',
  `SORT` int(3) DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_DICT_ITEM_DICT_ID` (`DICT_ID`),
  KEY `IDX_ITEM_CODE` (`ITEM_CODE`),
  KEY `IDX_ITEM_SORT` (`AUTO_ID`,`ITEM_CODE`,`SORT`),
  CONSTRAINT `FK_DICT_ITEM_DICT_ID` FOREIGN KEY (`DICT_ID`) REFERENCES `EP_SYS_DICT` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;

/*Table structure for table `EP_SYS_MAIN_ORDER` */

CREATE TABLE `EP_SYS_MAIN_ORDER` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ACCT_ID` int(10) unsigned NOT NULL,
  `BILL_AMOUNT` decimal(20,2) NOT NULL,
  `DELETE_FLAG` tinyint(1) DEFAULT '0',
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_BILL_ACCOUNT_ID` (`ACCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Table structure for table `EP_SYS_SOLUTION` */

CREATE TABLE `EP_SYS_SOLUTION` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '方案ID',
  `SLT_NAME` varchar(20) NOT NULL COMMENT '方案名称',
  `SLT_CODE` varchar(32) NOT NULL COMMENT '方案代码,用于确定具体方案',
  `SLT_TYPE` char(7) NOT NULL DEFAULT 'SLT_000' COMMENT '方案详情类型,用于确定方案详情子表',
  `VERSION` int(11) NOT NULL DEFAULT '0' COMMENT '版本号',
  `TRANS_PERMISSIONS` tinyint(1) DEFAULT '1' COMMENT '交易权限,默认开启',
  `FEE_TAKER` enum('PAYER','RECEIVER') DEFAULT 'PAYER' COMMENT '手续费承担方,PAYER为付款方承担,RECEIVER为收款方承担',
  `SETTLEMENT_CYCLE` int(3) DEFAULT '1' COMMENT '结算周期(自动结算),默认间隔1天',
  `MINIMUM_SETTLEMENT` decimal(20,2) DEFAULT '200.00' COMMENT '最低结算限额,默认200',
  `CURRENCY_TYPE` char(7) DEFAULT 'CRC_000' COMMENT '结算币种,默认美元(CRC_000)',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DELETE_FLAG` tinyint(1) NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COMMENT='方案表(产品线表)';

/*Table structure for table `EP_SYS_SOLUTION_BASE_CASHIER` */

CREATE TABLE `EP_SYS_SOLUTION_BASE_CASHIER` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '收银台方案详情ID',
  `SLT_ID` int(10) unsigned NOT NULL COMMENT '方案ID',
  `PATMENT_CUST_TYPE` enum('CORPORATION','PERSONAL','GOVERNMENT') NOT NULL DEFAULT 'CORPORATION' COMMENT '支付客户类型',
  `PAYMENT_TYPE` enum('ONLINE_BANK','GOPAY') NOT NULL DEFAULT 'GOPAY' COMMENT '支付渠道',
  `SORT` int(1) unsigned NOT NULL DEFAULT '0' COMMENT '支付渠道顺序下标',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DELETE_FLAG` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_SLT_BC_SLTID` (`SLT_ID`),
  CONSTRAINT `FK_SLT_BC_SLTID` FOREIGN KEY (`SLT_ID`) REFERENCES `EP_SYS_SOLUTION` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='基础收银台展示方案表';

/*Table structure for table `EP_SYS_SOLUTION_BASE_FEE` */

CREATE TABLE `EP_SYS_SOLUTION_BASE_FEE` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '手续费方案详情ID',
  `SLT_ID` int(10) unsigned NOT NULL COMMENT '方案ID',
  `PAYMENT_WAY` char(7) NOT NULL DEFAULT 'PMW_000' COMMENT '收费方式:按年收费(PMW_000);按笔收费(PMW_001);按区间收费(PMW_002)',
  `PAYMENT_METHOD` char(7) NOT NULL DEFAULT 'PMM_000' COMMENT '收费方法:固定手续费(PMM_000);自定义手续费(PMM_001);交易额手续费(PMM_002);成交比率手续费(PMM_003)',
  `STATIC_FEE` decimal(20,2) DEFAULT '0.00' COMMENT '定额手续费金额',
  `STATIC_SCALE` double DEFAULT '0.005' COMMENT '固定手续费率',
  `MAX_TRANS` decimal(20,2) DEFAULT '0.00' COMMENT '交易额区间上限,当PAYMENT_WAY为PMW_002时开启',
  `MIN_TRANS` decimal(20,2) DEFAULT '0.00' COMMENT '交易额区间下限,当PAYMENT_WAY为PMW_002时开启',
  `MAX_CHARGE` decimal(20,2) DEFAULT '0.00' COMMENT '收费上限,当PAYMENT_WAY为PMW_002且PAYMENT_METHOD为PMM_003时开启',
  `MIN_CHARGE` decimal(20,2) DEFAULT '0.00' COMMENT '收费下限,当PAYMENT_WAY为PMW_002且PAYMENT_METHOD为PMM_003时开启',
  `FEE_SCALE` double DEFAULT '0.005' COMMENT '收费比例,当PAYMENT_WAY为PMW_002且PAYMENT_METHOD为PMM_003,选择自定义手续费费率时开启',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DELETE_FLAG` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_SLT_BF_SLTID` (`SLT_ID`),
  CONSTRAINT `FK_SLT_BF_SLTID` FOREIGN KEY (`SLT_ID`) REFERENCES `EP_SYS_SOLUTION` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='手续费基础方案详情';

/*Table structure for table `EP_SYS_SOLUTION_SETTLEMENT_CHANEL` */

CREATE TABLE `EP_SYS_SOLUTION_SETTLEMENT_CHANEL` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '清算渠道方案详情ID',
  `SLT_ID` int(10) unsigned NOT NULL COMMENT '方案ID',
  `IS_ACTIVE` tinyint(1) DEFAULT '0' COMMENT '是否开通自动清算',
  `ACCT_ID` int(10) unsigned NOT NULL COMMENT '清算账户',
  `SETTLEMENT_BACK_ID` int(10) unsigned NOT NULL COMMENT '清算银行',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPADTE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `DELETE_FLAG` tinyint(1) DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_SLT_SC_SLTID` (`SLT_ID`),
  CONSTRAINT `FK_SLT_SC_SLTID` FOREIGN KEY (`SLT_ID`) REFERENCES `EP_SYS_SOLUTION` (`AUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='清算渠道方案详情表';

/*Table structure for table `EP_SYS_USER` */

CREATE TABLE `EP_SYS_USER` (
  `AUTO_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CUST_ID` int(10) unsigned NOT NULL,
  `USERNAME` varchar(40) NOT NULL,
  `PASSWD` varchar(160) NOT NULL,
  `REAL_NAME` varchar(60) NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DELETE_FLAG` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`AUTO_ID`),
  KEY `FK_USER_CUST_ID` (`CUST_ID`),
  CONSTRAINT `FK_USER_CUST_ID` FOREIGN KEY (`CUST_ID`) REFERENCES `EP_SYS_CUST` (`AUTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
